services:
  - type: web
    name: movie-recommender
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PORT
        value: 10000
